### ISSUE TITLE
month view

### ISSUE THREAD

**Issue by limdnas** [timtraversy/course_gnome_flutter#1]
hello.
Would there be a possibility to implement monthly view in a widget like https://github.com/apptreesoftware/flutter_calendar?

**Comment by timtraversy** [comment]
Hey! Sorry wasn’t tracking issues on this repo. I don’t plan to implement a monthly calendar because this app is currently only for building weekly schedules.

There are a bunch of calendar plugins though!
https://pub.dartlang.org/flutter/packages?q=Calendar
